INSERT INTO PROD.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (1, 'Janani');
INSERT INTO PROD.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (2, 'Karthik');
INSERT INTO PROD.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (3, 'Swetha');