CREATE TABLE PUBLIC.EMPLOYEES (
    EMP_ID INT,
    EMP_NAME VARCHAR
);

INSERT INTO PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (1, 'Janani');
INSERT INTO PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (2, 'Karthik');
INSERT INTO PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (3, 'Swetha');