INSERT INTO PROD_DB.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (1, 'Janani');
INSERT INTO PROD_DB.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (2, 'Karthik');
INSERT INTO PROD_DB.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (3, 'Swetha');
INSERT INTO PROD_DB.PUBLIC.EMPLOYEES (EMP_ID, EMP_NAME) VALUES (4, 'Anitha');